name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Checkout the repo.
      - uses: actions/checkout@v3

      # Set up Conda.
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      # Create and activate environment.
      - name: Create environment
        run: |
          conda install -c conda-forge mamba
          mamba env create -f dev_environment.yml
          conda init
          conda activate skysealand

      # Run devinstall.py to finish setup.
      - name: Dev install
        run: |
          conda activate skysealand
          python devinstall.py

      # Run pre-commit checks on all files.
      - name: Run pre-commit
        run: pre-commit run --all-files

      # Run MyPy type checks.
      - name: Run MyPy
        run: mypy .

      # Run Pyright type checks.
      - name: Run Pyright
        run: pyright

      # Run Pytest.
      - name: Run Pytest
        run: pytest --maxfail=5 --disable-warnings -q
