name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Set up Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      # Install Mamba
      - name: Install Mamba
        run: conda install -c conda-forge mamba

      # Create environment
      - name: Create environment
        run: mamba env create -f dev_environment.yml

      # Run devinstall.py inside the environment
      - name: Dev install
        run: conda run -n skysealand python devinstall.py

      # Run pre-commit checks
      - name: Run pre-commit
        run: conda run -n skysealand pre-commit run --all-files

      # Run MyPy
      - name: Run MyPy
        run: conda run -n skysealand mypy .

      # Run Pyright
      - name: Run Pyright
        run: conda run -n skysealand pyright

      # Run Pytest
      - name: Run Pytest
        run: conda run -n skysealand pytest --maxfail=5 --disable-warnings -q
